################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    sections:
    - title: Getting Access
      link: docs/getting-access/umm-access.md
      sections:
      - title: API Access
        link: docs/getting-access/api-access.md
      - title: Snowflake Access
        link: docs/getting-access/database-access.md
- sections:
    - title: UMM Merchant Data Specification
      sections:
        - title: Read Me
          link: docs/specification/readMe.md
        - title: Supported Backend Platforms
          link: docs/specification/supportedPlatforms.md
        - title: Merchant Data Auditing
          link: docs/specification/merchant/merchantAuditing.md
        - title: UMM Entities
          sections:
            - title: Merchant
              link: docs/specification/merchant/merchant.md
            - title: Merchant Business Information
            - title: Merchant Owner
              link: docs/specification/merchant/merchantOwner.md
              link: docs/specification/merchant/merchantBusinessInformation.md
            - title: Merchant Attributes
              link: docs/specification/merchant/merchantAttributes.md
- sections:
  - title: Release notes
    sections:
    - title: May 2024
      link: docs/release-notes/2024/may.md
# - sections:
#   - title: Working with UMM API
#     sections:
#     - title: Authentication
#       link: docs/authentication.md
#     - titlei: Attributes
#       sectons:
#       - title: Merchant
#         link: docs/attribute/merchant/details.md
# - sections:
#     - title: UMM Specifications
#       sections:
#         - title: Merchant
#           link: docs/definitions/Merchant.md
#         - title: Merchant Business Information
#           link: docs/definitions/MerchantBusinessInformation.md
