################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

# - sections:
#   - title: About
#     link: docs/about-umm/umm-overview.md
- sections:
  - title: Integrations
    # link: docs/getting-started.md
# - sections:
#   - title: Getting Access
#     link: docs/getting-access/umm-access.md
    sections:
    - title: API Access
      link: docs/getting-access/api-access.md
    - title: Snowflake Access
      link: docs/getting-access/database-access.md
    # sections:
    # - title: UMM Overview
    #   link: docs/getting-access/umm-overview.md
    # - title: Snowflake Access
    #   link: docs/getting-access/database-access.md
# - sections:
#   - title: Supported Backend Platforms
#     link: docs/specification/supportedPlatforms.md   
- sections:
  - title: Data Specification
    link: docs/specification/readMe.md
    sections:
    - title: Merchant
      link: docs/specification/merchant/merchant.md
      sections:
      - title: Address
        link: docs/specification/merchant/MerchantAddress.md
      - title: Attributes
        link: docs/specification/merchant/merchantAttributes.md
      - title: Bank Account
        link: docs/specification/merchant/MerchantBankAccount.md
      - title: Business Information
        link: docs/specification/merchant/MerchantBusinessInformation.md
      - title: Hierarchy
        link: docs/specification/merchant/MerchantHierarchy.md
      - title: Owner
        link: docs/specification/merchant/MerchantOwner.md
      - title: Tax Additional Data (US)
        link: docs/specification/merchant/Tax_Adtnl_Data_US.md
      - title: Xref
        link: docs/specification/merchant/Merchant_Xref.md
      - title: Product
        link: docs/specification/merchant/products.md   
        sections:
        - title: Merchant Product Entity
          link: docs/specification/merchant/merchantProduct.md
        - title: Merchant Product Attribute Entity
          link: docs/specification/merchant/ProductAttributes.md
        - title: Entitlement Attribute
          link: docs/specification/merchant/prodAttributes_Entitlements.md
        - title: Value Added Attribute
          link: docs/specification/merchant/productAttributes_VAS.md
        - title: Fee Attribute
          link:  docs/specification/merchant/productAttributes_fees.md
        - title: Equipment Attributes
          link:   docs/specification/merchant/productAttributes_equipment.md  
      - Title: Master Data
        link: docs/specification/master/master.md
        sections:
        - title: Domain Master
          link: docs/specification/master/domain_master.md

    # - title: Product
    #   link: docs/specification/merchant/merchantProduct.md
    #   sections:
    #   - title: Entitlements
    #     link: docs/specification/products_entitlements.md
    #   - title: Equipment
    #     link: docs/specification/products_equipments.md
    #   - title: Fees
    #     link: docs/specification/products_fees.md
    #   - title: Value Added Services
    #     link: docs/specification/products_vas.md
    # - title: Product Attributes
    #   link: docs/specification/merchant/ProductAttributes.md  
    #   sections:
    #   - title: Entitlements
    #     link: docs/specification/merchant/prodAttributes_Entitlements.md
    #   - title: Equipment
    #     link: docs/specification/merchant/productAttributes_equipment.md
    #   - title: Fees
    #     link: docs/specification/merchant/productAttributes_fees.md
    #   - title: Value Added Services
    #     link: docs/specification/merchant/productAttributes_VAS.md
- sections:
  - title: Auditing
    link: docs/specification/merchant/audit/merchantAuditing.md
    sections:
    - title: Audit Info
      link: docs/specification/merchant/audit/umm-audit-info.md
    - title: Audit Additional Info
      link: docs/specification/merchant/audit/umm-audit-additional-info.md    
- sections:
  - title: Release notes
    sections:
    - title: May 2024
      link: docs/release-notes/2024/may.md
