################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Unified Merchant Master
  productionDescription: UMM offers a unified/canonical data model for GBS Merchant Account & product offerings on a Snowflake Database with a CRUD interface and real time bi-directional synchronization with 5 backend merchant master databases (North, Optis, South, Memphis and OmniPay). With unification in data and API, it promotes ease of integration , low maintenance,  easy consumption of change and reduce development time for merchant onboarding and maintenance. It serves as a comprehensive analytical platform for merchant data. 
  whoIsItFor: Internal
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: UMM™
benefits:
  - title: Unified Data Model
    description: UMM provides a standardized data model for the Merchant, Equipment , Fee, and Product offerings. The data model is designed to be consistent across different backend merchant master to ensures all data is stored in a unified format, simplifying data integration and analysis.
  - title: Unified Merchant Master API Gateway
    description: Unified  API layer to retrieve, on-board or update merchant across Fiserv platforms in user-friendly and intuitive manner for easier integration
  - title: Real-time Bi-directional Synchronization
    description: UMM enables real-time synchronization with backend merchant master databases to ensures consistency and accuracy of the data across all systems.
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Unified Merchant data
    description: Fiserv has diverse and complex back-end merchant databases having significant variations in merchant details, hierarchy, product information, and pricing data. This lack of data structure uniformity poses considerable challenges for data consumption and integration, leading to increased complexity and turnaround time. Furthermore, the absence of this data in a single repository further complicates the process. UMM has consolidated the data into a unified format in a single repository for seamless data consumption and integration. 
    tags: ["UMM", "Merchant",  "Unified"]
    bullets: ["UMM", "Merchant"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL Merchant Inquiry API
        type: "post"
        path: "/graphql"
      - relatedAPI: 
        title: Merchant Search
        description: Unified GraphQL Merchant Search API
        type: "post"
        path: "/graphql⁣⁣"
  - title: Merchant OnBoarding 
    description: The Unified GraphQL Merchant Update API provides a simplified method to update merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    tags: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"      
  - title: Merchant Inquiry
    description: The Unified GraphQL Merchant Inquiry API provides a simplified method to access merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    bullets: ["UMM", "Merchant", "GraphQL", "Inquiry", "Search"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL Merchant Inquiry API
        type: "post"
        path: "/graphql"
      - relatedAPI: 
        title: Merchant Search
        description: Unified GraphQL Merchant Search API
        type: "post"
        path: "/graphql⁣⁣"
  - title: Merchant Maintenance 
    description: The Unified GraphQL Merchant Update API provides a simplified method to update merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    tags: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"
      # - relatedAPI: 
      #   title: Merchant Delete
      #   description: Unified GraphQL Merchant Delete API
      #   type: "post"
      #   path: "/graphql⁣⁣⁣"
  - title: Product Inquiry
    description:  Unified Product Inquiry API
    tags: ["UMM", "Product", "Inquiry"]
    bullets: ["UMM", "Product", "Inquiry"] 
    relatedDocs:
      - relatedDoc: 
        title: Products
        description: Products
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Product Inquiry
        description: Unified Product Inquiry API
        type: "get"
        path: "/internal/v1/products"
  - title: Auditing and Notification 
    description: The Unified GraphQL Merchant Update API provides a simplified method to update merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    tags: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"      