################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Unified Merchant Master
  productionDescription: UMM offers a unified/canonical data model for GBS Merchant Account & product offerings on a Snowflake Database with a CRUD interface and real time bi-directional synchronization with 5 backend merchant master databases (North, Optis, South, Memphis and OmniPay). With unification in data and API, it promotes ease of integration , low maintenance,  easy consumption of change and reduce development time for merchant onboarding and maintenance. It serves as a comprehensive analytical platform for merchant data. 
  whoIsItFor: Internal
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: UMM™
benefits:
  - title: Unified Data Lake
    description: Single database hosting merchant, equipment, fees & product data across Fiserv platforms in unified format
  - title: Simplified Integration
    description: Unified API layer to retrieve, on-board or update merchant across Fiserv platforms.
  - title: Analystics & Reporting
    description: Convert unstructured data into eays-to-read insight to make solid business decisions
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Merchant Inquiry
    description: Unified GraphQL Merchant Inquiry API
    tags: ["UMM", "Merchant", "GraphQL"]
    bullets: ["UMM", "Merchant", "GraphQL"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/merchant.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL merchant inquiry API
        type: "post"
        path: "/graphql"
  - title: Product Inquiry
    description:  Unified Product Inquiry API
    tags: ["UMM", "Product"]
    bullets: ["UMM", "Product"] 
    relatedDocs:
      - relatedDoc: 
        title: Products
        description: Products
        link: ./docs/products.md
      # - relatedDoc: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   link: ./docs/REPLACE-ME2.md
      # - relatedDoc: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   link: ./docs/REPLACE-ME3.md
    relatedAPIs:
      - relatedAPI: 
        title: Product Inquiry
        description: Unified Product Inquiry API
        type: "get"
        path: "/internal/v1/products"
      # - relatedAPI: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   type: "post"        
      #   path: "/v1/REPLACEME2"
      # - relatedAPI: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   type: "get"        
      #   path: "/v1/REPLACEME3"
