################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Unified Merchant Master
  productionDescription: UMM offers single unified definition of products & offerings, fees, equipment and merchant demographic information across multiple Fiserv platforms under one umbrella enabling real time access of data using unified API gateway leading to ease of integration, low maintenance, easy consumption of change and reduce development time. With unified/canonical data model on Snowflake & unified GraphQL API, it reduces friction in on-boarding, account maintenance, offering management product rollout & provides an easy interface for reconciliation and comprehensive analytics of merchant data
  whoIsItFor: Internal
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: UMM™
benefits:
  - title: Unification & Single source of truth for merchant data
    description: Single database hosting merchant , equipment , fees & product data across Fiserv platforms in unified format.
  - title: Simplified Integration
    description: Unified API layer to retrieve, on-board or update merchant across Fiserv platforms.
  - title: Real time Data sync capability
    description: Bi-directional data sync capability with backend merchant masters keeping UMM always in sync with backends at real time.
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Merchant Inquiry
    description: Unified GraphQL Merchant Inquiry API
    tags: ["UMM", "Merchant", "GraphQL"]
    bullets: ["UMM", "Merchant", "GraphQL"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/merchant.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL merchant inquiry API
        type: "post"
        path: "/graphql/getMerchant"
  - title: Product Inquiry
    description:  Unified Product Inquiry API
    tags: ["UMM", "Product"]
    bullets: ["UMM", "Product"] 
    relatedDocs:
      - relatedDoc: 
        title: Products
        description: Products
        link: ./docs/products.md
      # - relatedDoc: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   link: ./docs/REPLACE-ME2.md
      # - relatedDoc: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   link: ./docs/REPLACE-ME3.md
    relatedAPIs:
      - relatedAPI: 
        title: Product Inquiry
        description: Unified Product Inquiry API
        type: "get"
        path: "/internal/v1/products"
      # - relatedAPI: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   type: "post"        
      #   path: "/v1/REPLACEME2"
      # - relatedAPI: 
      #   title: REPLACEME
      #   description: REPLACEME
      #   type: "get"        
      #   path: "/v1/REPLACEME3"
