################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Unified Merchant Master
  productionDescription: UMM aims to offer a developer friendly and unified/canonical data model for GBS Merchant Account & product offerings, backed by Snowflake data store along with a standard CRUD interface and real time bi-directional synchronization with multiple backend merchant master databases (North, Optis, South, Memphis and OmniPay). With unification in data and API, it promotes ease of integration, low maintenance and easy consumption of change and reduce development time for merchant onboarding and maintenance. It serves as a comprehensive analytical platform for merchant data
  whoIsItFor: Internal
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: UMM™
benefits:
  - title: Unified Data Model
    description: UMM provides a unified data model for Merchant,Equipment,Fee and Product offerings to ensures consistency across different Merchant backends.
  - title: Unified Merchant Master API Gateway
    description: Unified  API layer to retrieve, on-board or update merchant across Fiserv platforms in user-friendly and intuitive manner for easier integration
  - title: Real-time Bi-directional Synchronization
    description: UMM enables real-time synchronization with backend merchant master databases to ensures consistency and accuracy of the data across all systems.
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Merchant On-boarding 
    description: The GraphQL Create API provides a simplified method to onboard a merchant across all platforms via an unified specification, removing the need for independent integrations with multiple backend systems in diverse formats
    tags: ["UMM", "Merchant", "GraphQL", "Create"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: /docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
  - title: Merchant Inquiry
    description: The GraphQL Inquiry API provides a simplified method to access merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats
    tags: ["UMM", "Merchant", "GraphQL", "Inquiry", "Search"]
    bullets: ["UMM", "Merchant", "GraphQL", "Inquiry", "Search"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: /docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL Merchant Inquiry API
        type: "post"
        path: "/graphql"
      - relatedAPI: 
        title: Merchant Search
        description: Unified GraphQL Merchant Search API
        type: "post"
        path: "/graphql⁣"
  - title: Merchant Maintenance 
    description: The GraphQL Update API provides a simplified method to update merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats
    tags: ["UMM", "Merchant", "GraphQL", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: /docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"
  - title: Product Inquiry
    description: Unified Product Inquiry API to retrieve all available products for a given backend and product category
    tags: ["UMM", "Product", "Inquiry"]
    bullets: ["UMM", "Product", "Inquiry"] 
    relatedDocs:
      - relatedDoc: 
        title: Products
        description: Products
        link: /docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Product Inquiry
        description: Unified Product Inquiry API
        type: "get"
        path: "/internal/v1/products"
  - title: Auditing and Notification 
    description: Maintains an audit log to record all changes made. Stores snapshots to provide historical data views, facilitating point-in-time analysis
    tags: ["UMM", "Merchant", "Audit"]
    bullets: ["UMM", "Merchant", "Audit"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: /docs/specification/merchant/audit/merchantAuditing.md
