################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName:  Unified Merchant Master
  productionDescription: > 
    Fiserv faces a significant challenge in managing multiple, diverse, and complex back-end merchant databases that lack a uniform definition for products, fees, pricing, merchant accounts, and acquiring hierarchy across platforms. The disparity in data taxonomy and conflicting semantics among different systems has resulted in substantial gaps in documentation and the absence of a single source of truth about a merchant. Additionally, the reliance on the availability of back-end services to access necessary data, combined with the distinct formats utilized by each backend system, complicates efficient data utilization. The presence of multiple copies of merchant data in downstream systems, tailored for specific purposes, further adds to the complexity, creating significant friction in processes like onboarding, account maintenance, offering management, and product rollout. Reconciling data and conducting comprehensive analytics of merchant information is also extremely challenging due to the lack of a co-located, unified data repository.
    \n
    To address these issues, the Unified Merchant Master (UMM) offers a comprehensive solution by providing a Single Unified Definition of products and offerings, fees, equipment, and merchant demographic information. UMM establishes a unified or canonical data model for GBS Merchant Account and product offerings, hosted on a Snowflake Database and enhanced with a CRUD interface. It ensures real-time bi-directional synchronization with five back-end merchant master databases (North, Optis, South, Memphis, and OmniPay). This standardization of data and APIs facilitates seamless integration, reduces maintenance overhead, and enables the easy adoption of changes, thereby significantly cutting down the development time for merchant onboarding and maintenance activities.
    \n
    By unifying data and APIs, UMM simplifies the integration process, reducing complexity and the need for extensive custom development. The standardized data model and enhanced integration capabilities significantly reduce the maintenance overhead traditionally associated with managing multiple disparate systems, and the development time required for merchant onboarding and maintenance activities is considerably accelerated. With a co-located, unified data repository in Snowflake, comprehensive and accurate analytics of merchant data become feasible, driving better business insights and decision-making. This results in improved data governance, operational efficiency, and advanced analytics capabilities, ultimately ensuring consistent, accurate, and actionable merchant data across the organization.

  whoIsItFor: Internal
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: UMM™
benefits:
  - title: Unified Data Model
    description: UMM provides a unified data model for Merchant,Equipment,Fee and Product offerings to ensures consistency across different Merchant backends.
  - title: Unified Merchant Master API Gateway
    description: Unified  API layer to retrieve, on-board or update merchant across Fiserv platforms in user-friendly and intuitive manner for easier integration
  - title: Real-time Bi-directional Synchronization
    description: UMM enables real-time synchronization with backend merchant master databases to ensures consistency and accuracy of the data across all systems.
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Unified Merchant data
    description: Fiserv has diverse and complex back-end merchant databases having significant variations in merchant details, hierarchy, product information, and pricing data. This lack of data structure uniformity poses considerable challenges for data consumption and integration, leading to increased complexity and turnaround time. Furthermore, the absence of this data in a single repository further complicates the process. UMM has consolidated the data into a unified format in a single repository for seamless data consumption and integration. 
    tags: ["UMM", "Merchant",  "Unified"]
    bullets: ["UMM", "Merchant"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL Merchant Inquiry API
        type: "post"
        path: "/graphql"
      - relatedAPI: 
        title: Merchant Search
        description: Unified GraphQL Merchant Search API
        type: "post"
        path: "/graphql⁣⁣"
  - title: Merchant OnBoarding 
    description: The Unified GraphQL Merchant OnBoarding API provides a simplified method to onboard a merchant  across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    tags: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"      
  - title: Merchant Inquiry
    description: The Unified GraphQL Merchant Inquiry API provides a simplified method to access merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    bullets: ["UMM", "Merchant", "GraphQL", "Inquiry", "Search"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Inquiry
        description: Unified GraphQL Merchant Inquiry API
        type: "post"
        path: "/graphql"
      - relatedAPI: 
        title: Merchant Search
        description: Unified GraphQL Merchant Search API
        type: "post"
        path: "/graphql⁣⁣"
  - title: Merchant Maintenance 
    description: The Unified GraphQL Merchant Update API provides a simplified method to update merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    tags: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"
      # - relatedAPI: 
      #   title: Merchant Delete
      #   description: Unified GraphQL Merchant Delete API
      #   type: "post"
      #   path: "/graphql⁣⁣⁣"
  - title: Product Inquiry
    description:  Unified Product Inquiry API
    tags: ["UMM", "Product", "Inquiry"]
    bullets: ["UMM", "Product", "Inquiry"] 
    relatedDocs:
      - relatedDoc: 
        title: Products
        description: Products
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Product Inquiry
        description: Unified Product Inquiry API
        type: "get"
        path: "/internal/v1/products"
  - title: Auditing and Notification 
    description: The Unified GraphQL Merchant Update API provides a simplified method to update merchant data across platforms in a unified manner, removing the need for independent integrations with multiple backend systems in diverse formats.
    tags: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    bullets: ["UMM", "Merchant", "GraphQL", "Create", "Update"]
    relatedDocs:
      - relatedDoc: 
        title: Merchant
        description: Merchant
        link: ./docs/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Merchant Create
        description: Unified GraphQL Merchant Create API
        type: "post"
        path: "/graphql⁣⁣⁣⁣"
      - relatedAPI: 
        title: Merchant Update
        description: Unified GraphQL Merchant Update API
        type: "post"
        path: "/graphql⁣⁣"      