################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################

openapi: 3.0.1
info:
  title: UMM Internal Service
  description: APIs to retrieve UMM master data
  version: 1.0.0
servers:
- url: https://connect.fiservapis.com/unifiedmerchantmaster
paths:
  /internal/v1/products:
    get:
      tags:
      - Product Inquiry
      summary: API to retrieve Products
      operationId: products
      parameters:
      - name: platformCode
        in: query
        description: Code to identify the specific backend platform. It adds the required
          information for the merchant
        required: true
        schema:
          type: string
          description: Code to identify the specific backend platform. It adds the
            required information for the merchant
          example: NORTH
          enum:
          - NORTH
          - OMAHA
          - SOUTH
          - OMNIPAY26
        example: NORTH
      - name: productCategory
        in: query
        required: true
        schema:
          type: string
          example: VAS
        example: VAS
      - name: productCode
        in: query
        description: Code that indicate the brand entitlement of the product
        required: false
        schema:
          type: string
          description: Code that indicate the brand entitlement of the product
      - name: productShortDescription
        in: query
        required: false
        schema:
          maxLength: 2147483647
          minLength: 4
          type: string
      - name: includeInactive
        in: query
        required: false
        schema:
          type: string
          example: true
        example: true
      - name: pageNumber
        in: query
        required: false
        schema:
          minLength: 1
          type: string
          example: 1
        example: 1
      - name: tags
        in: query
        required: false
        schema:
          maxLength: 10
          minLength: 0
          type: string
      - name: Authorization
        in: header
        description: Bearer token
        required: true
        schema:
          type: string
        example: "Bearer {token}"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductMasterResponse'
      x-proxy-name: v1/products
      x-group-name: Inquiry
      x-core: UMM
      x-child-product-name: Products
components:
  schemas:
    ProductMasterExternalCrossRefResponse:
      type: object
      properties:
        xrefPlatform:
          type: string
        xrefPlatformIdentifier:
          type: string
    ProductMasterResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int64
    ProductResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        productCode:
          type: string
          description: Code that indicate the brand entitlement of the product
        productLongDesc:
          type: string
        productShortDesc:
          type: string
        productSubCategory:
          type: string
        pricingConfigType:
          type: string
        feeTypeCode:
          type: string
        isActive:
          type: string
        productCategory:
          type: string
        crossReference:
          type: array
          items:
            $ref: '#/components/schemas/ProductMasterExternalCrossRefResponse'
